name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get published version
      id: version_info
      run: |
        ./gradlew
        VERSION_CODE="v""$(./gradlew printVersion -q)"
        echo $VERSION_CODE
        echo -n "::set-output name=VERSION_CODE::$VERSION_CODE"

    - name: Check verison matches tag
      if: ${{ steps.version_info.outputs.VERSION_CODE != github.ref_name }}
      run: exit 1

    - name: Publish with Gradle
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
